# Generated by Django 4.0.4 on 2022-05-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='script_pubkey',
            new_name='redeem_script',
        ),
    ]
