# Generated by Django 4.0.4 on 2022-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_script_pubkey_addresses_redeem_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='redeem_script',
            field=models.CharField(max_length=400),
        ),
    ]
