# Generated by Django 4.0.4 on 2022-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='script_pubkey',
        ),
        migrations.AddField(
            model_name='addresses',
            name='redeem_script',
            field=models.CharField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
