# Generated by Django 4.0.4 on 2022-05-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_addresses_script_pubkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='txn_input',
            new_name='txn_hex',
        ),
    ]
